apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: python-web-app
  namespace: argocd

spec:
  project: platform-apps

  source:
    repoURL: https://github.com/sanyo123/kubernetes-platform-engineering.git
    targetRevision: main
    path: helm/python-web-app

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: python-web-app

  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
