apiVersion: v1
kind: Pod

metadata:
  name: pvc-demo
  namespace: python-web-app

spec:
  containers:
    - name: pvc-demo
      image: busybox
      command:
        - sleep
        - "3600"

      volumeMounts:
        - name: persistent-storage
          mountPath: /data

  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: python-web-app-pvc