apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: python-web-app-pvc
  namespace: python-web-app

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard