apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-app

  template:
    metadata:
      labels:
        app: python-web-app

    spec:
      containers:
        - name: python-web-app
          image: python-web-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
