apiVersion: v1
kind: Pod

metadata:
  name: scheduling-demo
  namespace: python-web-app

spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - python-web-app
            topologyKey: kubernetes.io/hostname

  containers:
    - name: scheduling-demo
      image: busybox
      command:
        - sleep
        - "3600"