apiVersion: v1
kind: Pod
metadata:
  name: serviceaccount-rbac-test
  namespace: python-web-app
spec:
  serviceAccountName: python-web-app-sa

  containers:
    - name: test
      image: curlimages/curl:latest
      command: ["sleep", "3600"]

  restartPolicy: Never