apiVersion: v1
kind: Pod

metadata:
  name: taint-demo
  namespace: python-web-app

spec:
  containers:
    - name: taint-demo
      image: busybox
      command:
        - sleep
        - "3600"
  tolerations:
  - key: workload
    operator: Equal
    value: platform
    effect: NoSchedule