apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: python-web-app
  labels:
    azure.workload.identity/use: "true"

spec:
  serviceAccountName: python-web-app-sa

  containers:
    - name: test
      image: ghcr.io/azure/azure-workload-identity/msal-go
      env:
        - name: KEYVAULT_URL
          value: "https://aksplatdevukskv.vault.azure.net/"
        - name: SECRET_NAME
          value: "workload-identity-test"

  restartPolicy: Never