name: Repository Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-kubernetes:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: | 
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz -o kubeconform.tar.gz
          tar xf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform
      
      - name: Validate manifest
        run: | 
          if [ -d "kubernetes" ] && find kubernetes -type f \( -name "*.yaml" -o -name "*.yml" \) | grep -q .; then
            find kubernetes -type f \( -name "*.yaml" -o -name "*.yml" \) -print0 | xargs -0 kubeconform -strict -summary
          else
            echo "No Kubernetes manifests found. Skipping validation."
          fi